<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Employee extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Employee_model');
    } 

    /*
     * Listing of employee
     */
    function index()
    {
        $data['employee'] = $this->Employee_model->get_all_employee();
        
        $data['_view'] = 'employee/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new employee
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'nama' => $this->input->post('nama'),
				'email' => $this->input->post('email'),
				'telepon' => $this->input->post('telepon'),
            );
            
            $employee_id = $this->Employee_model->add_employee($params);
            redirect('employee/index');
        }
        else
        {            
            $data['_view'] = 'employee/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a employee
     */
    function edit($id)
    {   
        // check if the employee exists before trying to edit it
        $data['employee'] = $this->Employee_model->get_employee($id);
        
        if(isset($data['employee']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nama' => $this->input->post('nama'),
					'email' => $this->input->post('email'),
					'telepon' => $this->input->post('telepon'),
                );

                $this->Employee_model->update_employee($id,$params);            
                redirect('employee/index');
            }
            else
            {
                $data['_view'] = 'employee/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The employee you are trying to edit does not exist.');
    } 

    /*
     * Deleting employee
     */
    function remove($id)
    {
        $employee = $this->Employee_model->get_employee($id);

        // check if the employee exists before trying to delete it
        if(isset($employee['id']))
        {
            $this->Employee_model->delete_employee($id);
            redirect('employee/index');
        }
        else
            show_error('The employee you are trying to delete does not exist.');
    }
    
}
