<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Siswa extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Siswa_model');
    } 

    /*
     * Listing of siswa
     */
    function index()
    {
        $data['siswa'] = $this->Siswa_model->get_all_siswa();
        
        $data['_view'] = 'siswa/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new siswa
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'nis' => $this->input->post('nis'),
				'nama' => $this->input->post('nama'),
				'jenis_kelamin' => $this->input->post('jenis_kelamin'),
				'telp' => $this->input->post('telp'),
				'alamat' => $this->input->post('alamat'),
            );
            
            $siswa_id = $this->Siswa_model->add_siswa($params);
            redirect('siswa/index');
        }
        else
        {            
            $data['_view'] = 'siswa/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a siswa
     */
    function edit($id)
    {   
        // check if the siswa exists before trying to edit it
        $data['siswa'] = $this->Siswa_model->get_siswa($id);
        
        if(isset($data['siswa']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nis' => $this->input->post('nis'),
					'nama' => $this->input->post('nama'),
					'jenis_kelamin' => $this->input->post('jenis_kelamin'),
					'telp' => $this->input->post('telp'),
					'alamat' => $this->input->post('alamat'),
                );

                $this->Siswa_model->update_siswa($id,$params);            
                redirect('siswa/index');
            }
            else
            {
                $data['_view'] = 'siswa/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The siswa you are trying to edit does not exist.');
    } 

    /*
     * Deleting siswa
     */
    function remove($id)
    {
        $siswa = $this->Siswa_model->get_siswa($id);

        // check if the siswa exists before trying to delete it
        if(isset($siswa['id']))
        {
            $this->Siswa_model->delete_siswa($id);
            redirect('siswa/index');
        }
        else
            show_error('The siswa you are trying to delete does not exist.');
    }
    
}
