<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Employee_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get employee by id
     */
    function get_employee($id)
    {
        return $this->db->get_where('employee',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all employee
     */
    function get_all_employee()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('employee')->result_array();
    }
        
    /*
     * function to add new employee
     */
    function add_employee($params)
    {
        $this->db->insert('employee',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update employee
     */
    function update_employee($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('employee',$params);
    }
    
    /*
     * function to delete employee
     */
    function delete_employee($id)
    {
        return $this->db->delete('employee',array('id'=>$id));
    }
}
